api.lua, main.lua
待解决：auto_load 和 autoload_local_danmaku 都被启用时存在本地 xml 弹幕时的争用和优先级问题
暂无好的想法
=> feat: enhancing the use of `show_danmaku_keyboard` and fixing unexpected calls

api.lua
=> misc: optimized match

md5.lua
=> feat: add `md5.sum` function

api.lua, md5.lua
老实说我对 md5 中的 lua51 兼容性代码感到不满，但 [mingw-w64-mpv](https://packages.msys2.org/base/mingw-w64-mpv) 仍在使用 lua51，这使得 lua51 支持可能是有必要的
=> fix: lua interpreter compatibility

api.lua, main.lua
=> feat: improve loading hint message of danmaku

api.lua, main.lua
=> fix: episodeTitle records not updated

api.lua, main.lua
主要适配部分特殊条目的剧场版和 OVA，不过 SP 内容也实际受益
=> fix: episodeTitle should to record non-episode content

README.md, api.lua, render.lua
=> fix:  show danmaku error

api.lua
=> feat: optimize name extraction

api.lua, render.lua
添加更多fallback，增加适配能力
我本地环境下拿到的url长成这个格式`https://cn-bj-fx-01-08.bilivideo.com/upgcxcode/32/88/26299728832/26299728832-1-192.mp4?`，添加对此类型url的适配
=> fix: add more fallback

api.lua
~~我其实不确定 stream-open-filename 在这里的作用~~
懂了，其实是为 ytdl 播放服务的，暂且保留吧
=> misc: optimizing cid fallback

render.lua
=> fix: danmaku stuck#64

render.lua
Reverts Tony15246/uosc_danmaku#66
=> Revert "misc: optimize timer"

render.lua
=> misc: optimize timer

api.lua
另见 https://github.com/Tony15246/uosc_danmaku/pull/61#issuecomment-2473608994
顺便注意到 yt-dlp 的巴哈姆特支持也在进行中了：https://github.com/yt-dlp/yt-dlp/pull/11459
=> feat: add fallback for get bahamut danmaku

render.lua
=> feat: set `user-data` property for danmaku delay

api.lua, options.lua, render.lua
=> feat: add save danmaku function#76

README.md, api.lua, options.lua, render.lua
Close #76
#78 中的 bug 修复不在此 pr 范围内
=> feat: add `save_danmaku` option to save danmaku

render.lua
=> fix: stop unintended render

api.lua, main.lua, options.lua, render.lua
=> refactor: use osd-overlay for rendering osd message #90

api.lua, main.lua
add composite menu and change danmaku style during playback
=> feat: enhanced uosc menu Tony15246#59

main.lua, render.lua
key script-message immediately_save_danmaku "xml"
key script-message immediately_save_danmaku "ass"
=> feat:  Add the function of save danma when playing video #76

api.lua, main.lua, render.lua
重构弹幕加载机制，实现分文件保存弹幕，加载弹幕时整合加载
解决了 #100 中弹幕源更改不能实时生效的问题，现在弹幕源更改会实时生效
=> refactor: implement multi-file danmaku load system

api.lua, render.lua
=> fix: solve next episode danmaku load problem and wrong danmaku file deletion problem #106

api.lua
优化中间弹幕文件生成机制，生成每个中间弹幕文件时减少一次弹幕格式转换，同时提高中间弹幕文件的鲁棒性
=> refactor: change intermediate danmaku file format

api.lua
=> refactor: rewrite binary file with go

main.lua
=> misc: optimize code structure

api.lua, guess.lua, main.lua
基于 #123
重构媒体名称解析的实现，代码取自我另一个脚本：https://github.com/dyphire/trakt-scrobble/blob/main/guess.lua
=> feat: refactor media name parsing

main.lua
=> refactor: Optimize the style modification menu and add a reset button

api.lua, main.lua
解决 https://github.com/Tony15246/uosc_danmaku/pull/127#issuecomment-2616514790 提到的bug
=> fix: add history failure

api.lua, main.lua, render.lua
=> feat: add danmaku source delay menu #120

main.lua, render.lua
为解决 #138 提出的问题做准备，等待进一步添加根据弹幕内容时间进行延迟调整的功能
=> feat: add danmaku content menu

guess.lua
=> fix: unpack compatibility problem #143

api.lua
修复本地同目录洗版资源场景下的弹幕加载
修复 emby 不同服/不同版本下同一影视的弹幕加载
=> fix:  loading danmaku

api.lua
=> feat: add progress display when fetch_danmaku_all are loaded

api.lua
解决 https://github.com/Tony15246/uosc_danmaku/pull/151#issuecomment-2630536046 提到的url 场景无法加载额外弹幕源问题，顺便修复多线程支持引入的网络视频哈希弹幕获取失败
=> fix: solve autoload danamku for url failure and addon danmaku for url failure #151

api.lua
=> fix: hash matching failed to cause nil

extra.lua
=> misc: streamline code

main.lua
=> refactor: rewrite search anime logic #164

main.lua
https://github.com/Tony15246/uosc_danmaku/issues/164#issuecomment-2676830667
使用/api/v2/anime配合/api/v2/episodes的查询方案依旧存在缺失剧集信息的问题，进一步优化为/api/v2/anime配合/api/v2/bangumi的查询方案
由于弹弹play中的动画和bangumiId一一对应，理论上不存在查找不到bangumiId所对应动画的情况，故不考虑保留/api/v2/anime配合/api/v2/episodes的查询方案作为fallback
=> refactor: rewrite search anime using /api/v2/bangumi #164

api.lua, main.lua, render.lua
https://github.com/Tony15246/uosc_danmaku/pull/178#issuecomment-2686752552
修复异步弹幕转换导致的弹幕保存失败问题
删除了对保存ass格式弹幕的支持
=> fix: solve async save danmaku failure

extra.lua
=> fix: danmaku status not set correctly

apis/dandanplay.lua
fixes https://github.com/Tony15246/uosc_danmaku/issues/200
=> fix: danmaku related record is not saved correctly

apis/dandanplay.lua, main.lua, modules/menu.lua, modules/utils.lua
=> feat: make auto match stronger

README.md, modules/options.lua, modules/utils.lua
文档也被我的 vscode 格式化了（
选项预设的替换规则用于 #169 和 #207 中的案例
=> feat: add option to allow customization of additional title replacement rules

main.lua, modules/menu.lua, modules/utils.lua
尝试了下以 json 字符串形式存储后发现可以正常保存，当初测试的不够充分
改为 json 字符串形式后使功能扩展更加方便
=> feat: change the storage method of danmaku sources

main.lua
见 https://github.com/Tony15246/uosc_danmaku/pull/211#issuecomment-2750833757
本地简单测试了一下没有问题
=> refactor: reorgnize json record format

apis/dandanplay.lua
=> fix: continue if fetch danmaku failed

README.md
添加了 `slqy123/uosc_danmaku` 作为关联项目。
=> doc: add related projects

main.lua
Fixes https://github.com/Tony15246/uosc_danmaku/issues/219
=> fix: network playback scenarios do not correctly remove manually added danmaku sources

apis/dandanplay.lua, modules/menu.lua
=> refactor: make the structure of the danmaku request parameter more generic

apis/extra.lua, modules/base64.lua, modules/options.lua
进一步降低用户使用门槛，另见 #227 
特意新建了一个 tmdb 账号来申请一个专用的 api key
=> feat: introduce the base64 module and preset an api key for tmdb

README.md, apis/dandanplay.lua, modules/options.lua, modules/utils.lua
=> feat: add option to support excluding hash matches for mounted files

apis/dandanplay.lua, main.lua, modules/menu.lua, modules/render.lua
参见 https://github.com/Tony15246/uosc_danmaku/discussions/82#discussioncomment-13786234
顺便修复了一处保存弹幕函数调用时的函数名错误
=> misc: add bin file existence check

modules/md5.lua
=> misc: preserve usage consistency

modules/parse.lua, modules/render.lua
正确实现重复弹幕检测和处理
滚动弹幕改为以秒为单位进入渲染队列，优化整齐度
=> feat: optimized danmaku parsing and rendering

README.md, apis/dandanplay.lua, apis/extra.lua, main.lua, modules/menu.lua, modules/parse.lua, modules/render.lua, modules/utils.lua
实施 #210 中讨论的想法
部分解决 #138
编辑：大写所有全局变量
Close #197
=> feat: refactored delay functionality

apis/extra.lua
=> fix: global variable lowercase error

modules/utils.lua
之前的文件名对比取集数的方案遗漏了多季存放在同一目录的可能性
=> feat: optimized the episode extraction logic
