README.md, api.lua
调整后的正则匹配以应对以下文件命名：
```
Setoutsumi.01.2017.Amazon.WEB-DL.1080p.H264.DDP-HDCTV.mkv
Setoutsumi.01.2017.Amazon.WEB-DL.640x480.24fps.X265.10Bit.DDP-HDCTV.mkv
```
脚本配置文件中不能使用空格和引号
=> Fix: improve episode number match pattern

api.lua
上次的 pr 总感觉漏了什么
在此之前已经添加过对选项运行时更新的支持：
https://github.com/Tony15246/uosc_danmaku/blob/29ea82deaac14e2f6521d52634b76c720fc65ff9/api.lua#L43
但由于 auto_load 选项相关代码实现没有支持此特性，修复
注意：一些选项（包括 auto_load）的更新在当前文件下无法触发，播放下一文件时才会生效
=> fix: autoload option supports runtime updates

README.md, api.lua, main.lua
示例：
- 与 [embyToLocalPlayer](https://github.com/kjtsune/embyToLocalPlayer) 结合使用
https://github.com/user-attachments/assets/a97e388a-5a26-423f-99ef-c97ecada4b06
- 与 [mpv-torrserver](https://github.com/dyphire/mpv-config/blob/master/scripts/mpv-torrserver.lua) 结合使用
https://github.com/user-attachments/assets/719080c2-a5a5-4358-bc95-4d1984a8d71c
也适用于其他网络播放场景
PS: 预先添加了 [tsukimi](https://github.com/tsukinaha/tsukimi) 预计将提供的`{} - S{}E{}: {}`的媒体标题格式的匹配模式
=> feat: implement autoload danmaku for URL videos

api.lua
已经为网络文件实现，同样为本地文件实现此功能
从父目录名称中提取
一般本地父目录有自行命名的话往往是正确的中文名称，未作修改的话也能提取想要的罗马音/日文名/英文名。这些都可以直接用于弹弹play搜索
即使预填充内容不正确，也可以轻易清除。大多数情况下都是有益的
同时修复一个匹配模式错误
=> feat: try to prefill search content for local files

api.lua, main.lua
#16 实现的匹配模式我在测试后又调整过，不小心破坏了懒匹配模式
修复，并实现更通用的匹配模式。可能要麻烦你重新发布一次了（
添加 hint 信息，使条目更容易辨识，尤其是 #18 提到的同名条目问题
=> Fix: implement correct match

api.lua
过早地进行 url_decode 处理会导致原始代码剥离`:`导致第一种匹配模式失效
为 tsukimi 预留的第二种匹配模式过于通配和下面的匹配内容对不上，改为严格匹配
url_decode 的引入是为了适应更通用的网络播放场景，结果不小心破坏了最初实现的 emby 使用场景（
=> fix: correcting the use of url_decode

api.lua, main.lua, md5.lua
原本的实现在 Windows 上通过调用 PowerShell 执行命令计算哈希的方式效率比较低，改用纯 lua 实现的 md5 功能
感谢 [rkscv/danmaku](https://github.com/rkscv/danmaku/blob/main/danmaku.lua) 中的实现
=> feat: implementing hash with the new md5 module

api.lua
通过range请求头请求前16兆数据，转存为mp4视频以用于哈希计算。从而实现在线视频的自动哈希匹配。目前在我使用的两个emby公益服上使用暂无问题。这个方法的兼容性还有待确认。
=> feat: add online video hash match

README.md, api.lua, main.lua
我在几个 emby 服务上测试了下新的网络数据获取功能，发现有的可以有的无法获取。未能正常获取时会导致哈希匹配报错
修复
=> fix: url hash match error

api.lua
=> fix: get url streaming data

README.md, api.lua, main.lua, options.lua, render.lua
摆脱视频画幅限制，实现 #47 
不再依赖次字幕新特性，降低 mpv 最低版本要求（与 uosc 配合使用时）
不再占用字幕轨
改善弹幕平滑度
=> Refactor: use `osd-overlay` for rendering danmaku instead

api.lua, main.lua, render.lua
=> feat: add danmaku support for bilibli video playback

render.lua
修复linux上由于timer无法正确初始化导致的弹幕无法关闭的问题，顺便简化了根据帧率重设timer的fallback
经测试此初始化方法在windows上也能正确运行，根据帧率重设timer也正常
=> fix: solve timer initialize problem on linux

render.lua
=> fix: add back high fps fallback for timer

README.md, api.lua, options.lua, render.lua
添加新的重复弹幕处理方式，原有的 blockmode 会移除常规弹幕中的所有重复内容
优化 ass 标签处理，实现部分特殊弹幕的渲染支持
在测试 b 站高级弹幕的时候发现弹弹play 接口会自动过滤高级弹幕，将此获取方式改成和巴哈一样的回退处理
=> feat: add `merge_tolerance` option to allow merging of duplicate danmaku

api.lua
之前实现功能的时候忘记添加message输出，导致用户可能无法判断功能是否执行
=> misc: add clear-source osd output

api.lua, main.lua, options.lua
增强了`从源添加弹幕`菜单的功能，使得可以通过该菜单可视化地管理所有弹幕源，顺便完成了#88中的需求
Close #88
1. 删除用户添加的弹幕源
2. 屏蔽来自弹幕服务器的弹幕源
3. 解除对来自弹幕服务器的弹幕源的屏蔽
另外，由于`add_from_source`选项是弹幕源管理不透明的情况下的产物，现在用户已经可以通过该菜单进行方便的可视化弹幕源管理，因此将该可选配置项废除
=> feat: add source menu enhancement #88

main.lua
`open_input_menu_uosc`菜单中原本的 items 内容和 footnote 重复了，不再需要
=> optimize: prompt for currently associated danmaku in the related menu

api.lua
修复弹弹play官方弹幕库弹幕数量为0时，无法生成对应的弹幕文件所导致的找不到弹幕文件的弹幕加载失败
=> fix: solve 0 comment exception

api.lua, main.lua
Close #111
1. 修正了clear-source功能中误用ipairs导致的nil problem
2. 固定了ass文件中存储的字体名，以避免非英文字符编码问题
=> fix: solve clear-source fail problem and solve fontname encode problem #111

api.lua, extra.lua, main.lua, options.lua, render.lua
基于 #121 
实现 https://github.com/Tony15246/uosc_danmaku/issues/114#issuecomment-2606517060 中的部分想法
通过在搜索关键词后追加`|ds`, `|dy`和`|dm`等额外关键词触发新的 API 弹幕搜索（对应电视剧、电影、动漫）
它会获取弹弹play 的 API 支持解析的视频网站的对应播放链接，然后再通过调用弹弹play 的 API 来获取弹幕
PS：动漫不推荐使用它，弹弹play 的 api 要更强大（国漫的话可以使用它，更全）
~~还有些小细节待完善~~
功能示意：
https://github.com/user-attachments/assets/21add67b-2269-450c-8562-63d4bfde4da6
API 文档参考：https://www.eruyi.cn/thread-11578-1-1.html
=> feat: add new api support

main.lua
=> fix: style menu add density and scrolltime #132

api.lua, main.lua
解决此处提到的 https://github.com/Tony15246/uosc_danmaku/issues/120#issuecomment-2629301010 重新搜索弹幕并加载时没清空旧弹幕的问题
=> fix: clear api sever source when reset episode

api.lua, main.lua
https://github.com/Tony15246/uosc_danmaku/issues/120#issuecomment-2629214656
https://github.com/Tony15246/uosc_danmaku/issues/120#issuecomment-2629215925
完成以上两个需求，顺便解决 #147 引入的，盲目清空所有弹幕服务器弹幕源，导致历史记录中保存的延迟失效的bug
=> feat: add support for new time input format and hide blocked sources in delay menu

render.lua
- Hardcoded the outline color and shadow color to black (`\3c&H000000&\4c&H000000&`) in the subtitle rendering string.
弹幕描边和阴影颜色受`--osd-outline-color`（`--osd-border-color`）和`--osd-back-color`（`--osd-shadow-color`）控制。  
例如，在配合 mpv-lazy（[2024V3(EX)](https://github.com/hooke007/MPV_lazy/releases/tag/20241229)）使用的的情况下，由于 mpv-lazy 默认在 mpv.conf 中配置了`osd-border-color = "#FFFFFF"`，导致弹幕描边也变为白色，如图：
因此我希望直接指定描边颜色和阴影颜色，以避免OSD参数预期外的影响。
因为我没有自由修改颜色的需求，就直接采取硬编码ASS标签这样不太优雅的办法了（
=> fix: ensure danmaku visibility regardless of OSD options

main.lua
删除`main.lua` 第583行，之前异步执行残留的代码
=> misc: delete refactor residual

api.lua, options.lua
添加通过 url 链接获取弹幕的回退机制
目前，弹幕转换程序无法正确处理爱奇艺的 xml 弹幕，见：https://github.com/hihkm/DanmakuFactory/issues/105
=> feat: add a fallback mechanism for the danmaku url fetching method

api.lua
~~按钮设置在 init() 调用的各个函数中会自动执行，无需提前设置，反而导致重复调用 init()~~
=> fix: repeat initialization

api.lua
使用`add_danmaku_source_local`添加弹幕源会把弹幕源在图形界面里的名称显示为本地文件的路径。这原本没什么问题，但是现在有了`get_danmaku_fallback`，会有很多网络弹幕源的弹幕被下载到本地进行加载，这时如果调用`add_danmaku_source_local`，就只会显示本地文件路径，让人搞不清楚这些弹幕源究竟是哪的弹幕源。因此添加了`save_danmaku_downloaded`专门处理网络弹幕源的弹幕被下载到本地进行加载的情况，使其能够显示弹幕来源的url。
顺便补上了一处之前漏掉的校验，有一处地方在修改弹幕源对应的弹幕文件之前忘记确认旧弹幕文件是否被删除。
=> misc: show real url for user added danmaku source

api.lua, render.lua
由于不只是电影电视剧，正常的从源添加弹幕有时也会回落到`get_danmaku_fallback`函数。而由于`get_danmaku_fallback`设置的弹幕文件名的重复，会导致新fallback到`get_danmaku_fallback`函数获取的弹幕，会覆盖之前别的fallback的弹幕源的弹幕。因此添加了count作为唯一标识，避免弹幕文件名重复。
=> fix: duplicate danmaku filename when fallback

apis/dandanplay.lua, main.lua
另见 https://github.com/hihkm/DanmakuFactory/pull/106
这不适用于本地 xml 文件，若遇到此类弹幕文件用户依然需要手动启用选项修复
=> fix: danmaku of iqiyi's source was not correctly handled

main.lua, modules/menu.lua
由于浮点运算的精度损失，多次调整延迟时可能会出现 `2.7755575615629e-17` 这样的异常显示。
另外，`+1e-10` 是为了防止 `-0.0` 的情况出现。
=> 优化弹幕延迟的显示格式

apis/extra.lua
=> fix: solve query_tmdb movie failure

apis/dandanplay.lua, modules/guess.lua, modules/utils.lua
这是更正确的实现方式
之前添加`chinese_to_number`功能就是为了增强媒体名解析，当时测试时有点问题就没添加（
在此 PR 中正确实施它
=> feat: optimized media name parsing

modules/parse.lua, modules/render.lua
Close #291 
之前的弹幕排布逻辑算法只考虑了追击问题时的情况。但实际上存在一种极端的小概率情况，就是前一条弹幕实在太长，长到后一条弹幕直接渲染在了前一条弹幕之上。
根据追击距离`delta_x `的公式`delta_x = (appear_time - previous_appear_time) * previous_velocity - (previous_length + text_length) / 2`，以及追击速度`delta_velocity`的公式`delta_velocity = velocity - previous_velocity`，只要`delta_x > = 0`且`delta_velocity < 0`，理论上就不可能被追上。举个例子，前一条弹幕长度为100px，后一条弹幕长度为1px。假设满足`delta_x > 0`，这只能证明前一条弹幕在后一条弹幕出现之前行进了大于两条弹幕长度一半的距离，也就是50px（短弹幕过短忽略不计），此时前一条弹幕还完全没有渲染完，还有将近一般的长度隐藏在屏幕右侧。这时后一条弹幕就会直接渲染在前一条弹幕上，出现弹幕重叠。又由于短弹幕速度慢于长弹幕，追击速度为负，也就是`delta_velocity < 0`，完美满足了不会被追击的条件。导致重叠弹幕通过条件判断最终被渲染。
也就是说只要前一条弹幕在后一条弹幕出现之前，没有通过长度为`previous_length`的距离，也就是`(appear_time - previous_appear_time) * previous_velocity < previous_length`，后一条弹幕就会跳过追击阶段，直接渲染在前一条弹幕之上。因此需要保证后一条弹幕的出现时间至少要晚于前一条弹幕完全渲染完成的时间戳。 …
=> fix: danmaku overlapping in right part of screen #291

README.md, apis/dandanplay.lua, modules/options.lua
This pull request introduces a new feature that allows users to exclude specific danmaku (comment) sources from certain platforms when loading more danmaku. The change adds support for keyword-based domain filtering, improves configuration options, and updates documentation to explain usage.
* Added the `excluded_platforms` option to `modules/options.lua`, allowing users to specify a list of platform domains to exclude from danmaku sources.
* Implemented the `filter_excluded_platforms` function in `apis/dandanplay.lua` to filter out related danmaku sources matching any of the excluded platform keywords.
* Updated the danmaku loading logic in `fetch_danmaku_all` to use the filtered list of sources, ensuring excluded platforms are not loaded.
* Added a new section in `README.md` that …
=> feat: add `excluded_platforms` option
